name: Release to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,cicd]"
      - name: Build and publish
        run: |
          tox -e build
          python -m twine check dist/*
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
